version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0

commands:
  cmd_echo:
    steps:
      - buildevents/berun:
          bename: echo
          becommand: |
            echo "hello"
            TXT=world
            echo $TXT

jobs:
  setup:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/start_trace

  watch:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/watch_build_and_finish

  echo:
    docker:
      - image: cimg/base:2021.04
    steps:
      - buildevents/with_job_span:
          steps:
            - cmd_echo

workflows:
  test:
    jobs:
      - setup
      - watch:
          requires:
            - setup
      - echo:
          requires:
            - setup
