version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0

commands:
  echo_txt:
    steps:
      - buildevents/berun:
          bename: echo with just text
          becommand: |
            echo hello

  echo_using_env_var:
    steps:
      - buildevents/berun:
          bename: echo with local env var
          becommand: |
            echo hello
            TXT=world
            echo $TXT
  
  echo_using_dummy_before_env_var:
    steps:
      - buildevents/berun:
          bename: echo with dummy before setting env var
          becommand: |
            echo
            TXT=world
            echo ${TXT}
            echo hello

  failing_echo_using_env_var_first:
    steps:
      - buildevents/berun:
          bename: echo with local env var first
          becommand: |
            TXT=world
            echo ${TXT}
            echo hello

  failing_mkdir:
    steps:
      - buildevents/berun:
          bename: echo
          becommand: |
            echo ${PWD}
            mkdir test
            cd ${PWD}/test


jobs:
  setup:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/start_trace

  watch:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/watch_build_and_finish

  echo:
    docker:
      - image: cimg/base:2021.04
    steps:
      - buildevents/with_job_span:
          steps:
            - echo_txt
            - echo_using_env_var
            - failing_echo_using_env_var_first
            - failing_mkdir

workflows:
  test:
    jobs:
      - setup
      - watch:
          requires:
            - setup
      - echo:
          requires:
            - setup
