version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0

jobs:
  echo:
    docker:
      - image: cimg/base:2021.04
    steps:
      - buildevents/with_job_span:
          steps:
            - buildevents/berun:
                bename: echo
                becommand: |
                  echo "hello"
                  TXT=world
                  echo $TXT

workflows:
  test:
    jobs:
      - echo
